### ISSUE TITLE
Non-ROS build

### ISSUE THREAD

**Issue by vebjornjr** [hbanzhaf/steering_functions#16]
Hi again!

Have you considered separating the core logic and the ROS code such that this library can be used in a non-ROS context?
At the moment, it's not possible to use this library without ROS due to catkin in the CMakeLists.txt file. (Except by manually copying the source files into the non-ROS project, ugh).

[Here](https://tuebel.github.io/blog/ros/cmake/2020/06/27/ros-plain-cmake.html) is an example of how to setup pure/plain CMake + catkin package.

I can take a look at this (with perhaps some testing and feedback) if you approve of this change.

**Comment by hbanzhaf** [comment]
Okay to me. @Timple: What do you think?

**Comment by Timple** [comment]
Sounds good to me!

There are multiple examples of packages available that can be compiled without ROS:

https://github.com/Neargye/magic_enum
https://github.com/RoboSense-LiDAR/rslidar_sdk
https://github.com/introlab/rtabmap

I would not advice to include the `plain_cmake` dependency as per your link. Because this cannot be resolved by rosdep (it's missing from this database: https://github.com/ros/rosdistro/search?q=plain_cmake

So this would either need to be added there, or a different approach should be followed such as the packages I mentioned.
